#!/usr/bin/env bash
# USAGE: ,aider [args]
# DESCRIPTION: Wrapper around aider

aider_args=()
aider_args+=('--no-show-model-warnings')
aider_args+=('--dark-mode')
aider_args+=('--auto-commits')

exec aider "${aider_args[@]}"

