#!/usr/bin/env bash
# USAGE: ,ask python <question>
# DESCRIPTION: Ask a Python question

question="$*"
if [[ -z "$question" ]]; then
	print-usage ',ask python <question>'
	print-error 'No question provided.'
	exit 1
fi

read -r -d '' system_prompt << EOF
<context>
You are an expert Python programmer.
You write code that is efficient, concise, and follows best practices.
</context>

<task>
Just provide code with no extra explanations.
If Python libraries need to be installed, provide pip command.
</task>

<coding_guidelines>
- No obvious comments.
- When using print(), add a comment of the expected output.
- Do not define function unless asked.
- Run shell commands using the list form.
</coding_guidelines>
EOF

exec ai --system-prompt "$system_prompt" --prompt "$question"

