#!/usr/bin/env bash
# USAGE: ,ask python <question>
# DESCRIPTION: Ask a Python question

question="$*"
if [[ -z "$question" ]]; then
	print-usage ',ask python <question>'
	print-error 'No question provided.'
	exit 1
fi

read -r -d '' system_prompt << EOF
You are an expert Python programmer.
Just provide code. No need for extra explanations.
If Python libraries need to be installed, provide pip command.
Shell commands should be run using the list form.
No obvious comments.
Avoid defining a function unless asked.
EOF

exec ai --system-prompt "$system_prompt" --prompt "$question"

