#!/usr/bin/env bash
# USAGE: ,ask bash <question>
# DESCRIPTION: Ask a question about Bash scripting

read -r -d '' system_prompt << 'EOF'
<context>
You will be given the output of `git diff`.
</context>

<task>
Write a clear and concise summary of important changes and their impact for a git commit message.
</task>

<custom_instructions>
Just return the commit message, do not include any other text.
If the file is new, say 'new' somewhere in the message.
Unimportant changes do not need to be mentioned.
If the diff is empty, say so.
</custom_instructions>

<good_example>
write-commit-msg: Add a new <context> section
</good_example>
<bad_example>
Updated system prompt in the 'write-commit'-msg file to include a new <context> section, clarifying the input details for the task.
</bad_example>
EOF
#echo "$system_prompt"; exit

question="$(git diff --staged)"
exec ai --system-prompt "$system_prompt" --prompt "$question"

