#!/usr/bin/env bash

print-header 'Claude Code'
print-url 'https://docs.anthropic.com/en/docs/claude-code'
print-url 'https://github.com/anthropics/claude-code'
print-url 'https://docs.anthropic.com/en/docs/claude-code/hooks'

echo
print-header 'Basic Commands'
cat <<-EOF
claude --dangerously-skip-permissions

# Continue most recent conversation
claude --continue
# Resume a specific conversation
claude --resume

# Non-interactive mode (for scripts)
claude --print "your prompt here"

# Commands
\`/init\` create CLAUDE.md file for codebase
\`/model\` to switch which model
\`/context\` to show context usage
\`/cost\` to show cost
\`/plugin\` for plugins
\`/rewind\` to go back in time
EOF

echo
print-header 'Environment'
print-url 'https://docs.claude.com/en/docs/claude-code/settings#environment-variables'
cat <<-EOF
export ANTHROPIC_BASE_URL="<url>"
export ANTHROPIC_MODEL="<model-name>"
export ANTHROPIC_AUTH_TOKEN="\$(cat ~/.claude_apitoken)"
EOF


echo
print-header 'Tips'
cat <<-EOF
- Create a \`.claude/settings.json\` in your project directory
- Create custom commands in \`.claude/commands/\`
- <Esc><Esc> to open conversation history
- S-<Tab> \`plan mode\`  or \`auto-accept edits on\`
- Keywords:
  - "ultrathink"
  - "subagent"
- Mention files that might be useful.
- When telling it not to do something, tell it what to do instead.
- \`/catchup\` to read all changed files in current branch.
- Instead or providing a bunch of flags, provide a bash wrapper script.
EOF

