#!/usr/bin/env bash
print-header 'LSF Commands'
cat <<-EOF
bjobs -UF <jobid>
bhist -l -n 0 <jobid>

bparams -l
bqueues -l <queue-name>
EOF

#echo
#print-header 'LSF Resources'

echo
print-header 'Termination Reasons'
print-url 'https://www.bsc.es/support/LSF/9.1.2/lsf_admin/index.htm?termination_reasons_lsf.html~main'
cat <<-EOF
0 - TERM_UNKNOWN: LSF cannot determine a termination reason—0 is logged but TERM_UNKNOWN is not displayed
1 - TERM_PREEMPT: Job killed after preemption
2 - TERM_WINDOW: Job killed after queue run window closed
3 - TERM_LOAD: Job killed after load exceeds threshold
4 - TERM_OTHER: Member of a chunk job in WAIT state killed and requeued after being switched to another queue.
5 - TERM_RUNLIMIT: Job killed after reaching LSF run time limit
6 - TERM_DEADLINE: Job killed after deadline expires
7 - TERM_PROCESSLIMIT: Job killed after reaching LSF process limit
8 - TERM_FORCE_OWNER: Job killed by owner without time for cleanup
9 - TERM_FORCE_ADMIN: Job killed by root or LSF administrator without time for cleanup
10 - TERM_REQUEUE_OWNER: Job killed and requeued by owner
11 - TERM_REQUEUE_ADMIN: Job killed and requeued by root or LSF administrator
12 - TERM_CPULIMIT: Job killed after reaching LSF CPU usage limit
13 - TERM_CHKPNT: Job killed after checkpointing
14 - TERM_OWNER: Job killed by owner
15 - TERM_ADMIN: Job killed by root or LSF administrator
16 - TERM_MEMLIMIT: Job killed after reaching LSF memory usage limit
17 - TERM_EXTERNAL_SIGNAL: Job killed by a signal external to LSF
18 - TERM_RMS: Job exited from an RMS system error
19 - TERM_ZOMBIE: Job exited while LSF is not available
20 - TERM_SWAP: Job killed after reaching LSF swap usage limit
21 - TERM_THREADLIMIT: Job killed after reaching LSF thread limit
23 - TERM_BUCKET_KILL: Job killed with bkill -b
25 - TERM_CWD_NOTEXIST: Current working directory is not accessible or does not exist on the execution host
26 - TERM_REMOVE_HUNG_JOB: Job removed from LSF[14:42:43] Finished in 0.029s
EOF

echo
print-header 'Absolute Priority Scheduling (APS)'
print-url 'https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=priorities-absolute-priority-scheduling'
cat <<-EOF
bjobs -aps
bmod -aps "system=10.00" <jobid>
bmod -aps "admin=10.00" <jobid>
bmod -apsn <jobid>

bjobs -l <jobid>
bhist -l <jobid>
EOF

