#!/usr/bin/env bash
print-header 'GIT'
print-url 'https://github.com/GitAlias/gitalias'
print-url 'https://wizardzines.com/comics/inside-git'

echo
print-header 'Commands'
cat <<-EOF
# Check for merge conflicts without merging
git merge-tree --write-tree main branch/name
EOF


echo
print-header 'Merge Conflicts'
echo -e "$(cat << EOF
\e[33m<<<<<<< HEAD\e[0m
These are changes from the \e[31;1mcurrent branch\e[0m.
\e[33m||||||| <common-ancestor>\e[0m
These are changes from the \e[32;1mcommon ancestor\e[0m.
\e[33m=======\e[0m
These are changes from the \e[31;1mincoming branch or stash\e[0m.
\e[33m>>>>>>> feature2\e[0m
EOF
)"


echo
print-header '.git'
echo -e "$(cat << EOF
.git/HEAD
.git/refs/heads/main
.git/logs/refs/heads/main
.git/refs/remotes/origin/main

# git cat-file -p <blob>
.git/objects/<blob>

.git/config
.git/hooks
.git/index
EOF
)"

