#!/usr/bin/env bash

print-header 'Claude Code'
print-url 'https://docs.anthropic.com/en/docs/claude-code'
print-url 'https://github.com/anthropics/claude-code'
print-url 'https://docs.anthropic.com/en/docs/claude-code/hooks'

echo
print-header 'Basic Commands'
cat <<-EOF
claude --dangerously-skip-permissions

# Continue most recent conversation
claude --continue
# Resume a specific conversation
claude --resume

# Non-interactive mode (for scripts)
claude --print "your prompt here"

# Commands
\`/init\` create CLAUDE.md file for codebase
\`/model\` to switch which model
EOF

echo
print-header 'Tips'
cat <<-EOF
- Create a \`.claude/settings.json\` in your project directory
- Create custom commands in \`.claude/commands/\`
- <Esc><Esc> to open conversation history
- S-<Tab> \`plan mode\`  or \`auto-accept edits on\`
- "ultrathink"
- "subagent"
EOF

