#!/usr/bin/env bash

print-header 'HEREDOC'
cat <<'HEREDOC'
# Here string
tr ':' '\n' <<< $PATH

# Here doc
cat <<'EOF'
Hello, world!
Bye bye.
EOF
HEREDOC

echo
print-header 'VARIABLES'
cat <<'EOF'
"$0" │ Script name/path. (Unreliable)
"$1" │ Positional parameters.
"$*" │ String of all parameters.
"$@" │ List of all parameters.
$#   │ Number of parameters.
$?   │ Most recent exit code.
$$   │ PID of current shell.
$!   │ PID of most recenet command.
"$_" │ Last argument of most recent command.
EOF


echo
print-header 'PARAMETER EXPANSION'
cat <<'EOF'
${parameter:-word}         │ Use 'word' if parameter is unset.
${parameter:=word}         │ Assign 'word` if parameter is unset.
${parameter:+word}         │ Use 'word' if paramter is set.
${parameter:offset:length} │ Substring.
${#parameter}              │ Length.
${parameter#pattern}       │ Delete shortest pattern from the beginning.
${parameter##pattern}      │ Delete longest pattern from the beginning.
${parameter%pattern}       │ Delete shortest pattern from the end.
${parameter%%pattern}      │ Delete longest pattern from the end.
${parameter/pat/string}    │ Replace first match of 'pat' with 'string'.
${parameter//pat/string}   │ Replace all matches of 'pat' with 'string'.
${parameter/#pat/string}   │ Replaces 'pat' with 'string' matched against the beginning.
${parameter/%pat/string}   │ Replaces 'pat' with 'string' matched against the beginning.
EOF

echo
print-header 'STRING MANIPULATION'
cat <<'EOF'
${word^^}                  │ Convert to uppercase.
${word^}                   │ Convert first character to uppercase.
${word,,}                  │ Convert to lowercase.
${word,}                   │ Convert first character to lowercase.
EOF

echo
print-header 'DECLARE'
cat <<'EOF'
declare -i  │ Variable is treated as integer
EOF
