#!/usr/bin/env bash

print-header 'HTTP Status Codes'
cat <<-EOF
200 OK

# 3xx Redirection
301 Moved Permanently
302 Found
303 See Other
304 Not Modified
307 Temporary Redirect
308 Permanent Redirect

# 4xx Client Errors
400 Bad Request
401 Unauthorized
403 Forbidden
404 Not Found
429 Too Many Requests

# 5xx Server Errors
500 Internal Server Error
501 Not Implemented
502 Bad Gateway
503 Service Unavailable
504 Gateway Timeout
EOF
