#!/usr/bin/env bash

# Pause media
,media pause

# Pause Dunst notifications
# https://wiki.archlinux.org/title/Dunst#Disable_dunst_temporarily
killall -SIGUSR1 dunst

i3lock_args=(--show-failed-attempts)
i3lock_args+=(--ignore-empty-password)
i3lock_args+=(--color=101030)

# Check background image
background="$HOME/.config/i3/background.png"
if [[ -f "$background" ]]; then
	i3lock_args+=(--image="$background")
	i3lock_args+=(--tiling)
fi
i3lock "${i3lock_args[@]}" &

# Unlock with fingerprint by killing i3lock on successful fprintd-verify
if command -v fprintd-verify > /dev/null; then
	(while pkill -0 i3lock 2>/dev/null; do
		fprintd-verify "$USER" && pkill i3lock && break
	done) &
fi

wait

# Resume Dunst notifications
# https://wiki.archlinux.org/title/Dunst#Disable_dunst_temporarily
killall -SIGUSR2 dunst

