#!/usr/bin/env bash
if [[ -n "$WAYLAND_DISPLAY" ]]; then
	if ! (type grim &>/dev/null && type slurp &>/dev/null); then
		print-cmd sudo apt install -y grim slurp
		exit 2
	fi
else
	if ! (type scrot &>/dev/null); then
		print-cmd sudo apt install -y scrot
		exit 2
	fi
fi

screenshot_dir="${XDG_CONFIG_HOME:-$HOME/.config}/screenshots"

if ! [[ -d "$screenshot_dir" ]]; then
	tmpdir="$(mktemp -d)"
	ln -fns "$tmpdir" "$screenshot_dir"
fi

cd "$screenshot_dir" || exit $?
if [[ -n "$WAYLAND_DISPLAY" ]]; then
	grim -g "$(slurp)" "$(date '+%Y-%m-%d-%H%M%S')_grim.png"
else
	scrot -s
fi

# Get screenshot
screenshot="$screenshot_dir/$(ls -t "$screenshot_dir" | head -n 1)"
cp-image "$screenshot"
