#!/usr/bin/env bash
# USAGE: aerospace-work
# DESCRIPTION: TODO

# Map specifc apps to specific spaces
declare -A apps
num_displays="$(mac-display-count)"

apps['1Password']=1
apps['Code']=5
apps['Cursor']=5
apps['iTerm2']=4
apps['Gmail']=7
apps['Slack']=7
apps['Google Calendar']=7
apps['ChatGPT']=7
apps['Spotify']=8
apps['WhatsApp Web']=9

while read line; do
	id="$(   jq -r '."window-id"'    <<<"$line")"
	space="$(jq -r '."workspace"'    <<<"$line")"
	app="$(  jq -r '."app-name"'     <<<"$line")"
	title="$(jq -r '."window-title"' <<<"$line")"
	#echo "id:$id space:$space app:$app title:$title"; continue

	[[ -z "$id" ]] && continue
	#echo "id:$id space:$space app:$app title:$title"; continue

	new_space='1'

	if [[ -v apps[$app] ]]; then
		new_space="${apps[$app]}"
	elif [[ "$app" == "Google Chrome" ]] || [[ "$app" == 'Brave Browser' ]]; then
		chrome_space="$(sed -n 's/\([1-9]\):.*/\1/p' <<<"$title")"
		if [[ -n "$chrome_space" ]]; then
			new_space="$chrome_space"
		fi
	fi

	#echo "id:$id space:$space app:$app title:$title"
	[[ "$space" == "$new_space" ]] && continue

	#echo "Move from $space to $new_space: ($id) $app '$title'"
	#continue
	aerospace-move-window-to-space "$id" "$new_space" </dev/null
done < <(aerospace-ls-windows)

