#!/usr/bin/env bash
# USAGE: aoc [year] [day]
# DESCRIPTION: Create a new AoC day directory with a template file

# ==============================================================================
# GET DATE
# ==============================================================================
year="$1"
day="$((10#$2))"

#current="$(date +'%Y%d')"
current="$(TZ=America/New_York date +%Y%d)"

[[ -z "$year" ]] && year="${current:0:4}"
[[ -z "$day" ]] && day="${current:4:2}"

year="$((year % 100 + 2000))"
day="$(printf "%02d" "$day")"


# ==============================================================================
# SET UP DIRECTORY
# ==============================================================================
# Get template
top="$(git-top)" || exit $?
cd "$top" || exit $?
ls -lrth 'template.rb' >/dev/null || exit $?
template="$top/template.rb"

mkdir -p "$year/$day" || exit $?
cd "$year/$day" || exit $?
cp -n "$template" a.rb

aoc-check-input 'input.txt' || aoc-download "$year" "$day" "$session" > 'input.txt'


# ==============================================================================
# OPEN TMUX
# ==============================================================================
dir="$(pwd)"
echo
echo 'Directory:'
echo "$dir"
if [[ -e ${TMUX%%,*} ]]; then
	tmux new-window -c "$dir" -n "$year-$day"
	tmux split-window -h -c "$dir" aoc-repl
	tmux split-window -v -l 2 -c "$dir"
	tmux select-pane -t 2
	tmux select-pane -t 1
	tmux send-keys 'vi *' C-m
fi

