#!/usr/bin/env bash

if ((${#@} != 5)); then
	print-usage "aoc-submit <session> <year> <day> <level> <answer>"
	exit 1
fi

session="$1"
year="$2"
day="$3"
level="$4"
answer="$5"

day="$((10#$day))"
year="$((year % 100 + 2000))"
data_raw="level=$level&answer=$answer"

now="$(date +'%Y%m%d-%H%M%S')"

url="https://adventofcode.com/$year/day/$day/answer"
curl_args=()
curl_args+=(--cookie "session=$session")
curl_args+=(--data-raw "$data_raw")

request_txt=".request_${now}.txt"
(
	echo "$url"
	echo "$data_raw"
) > ".request_${now}.txt"
ln -fns "$request_txt" '.request.txt'

response_txt=".response_${now}.txt"
print-cmd curl "${curl_args[@]}" "$url"
touch "$response_txt"
curl "${curl_args[@]}" "$url" > "$response_txt"
ln -fns "$response_txt" '.response.txt'

