#!/usr/bin/env bash
# USAGE: aoc-download <year> <day> [session]
# DESCRIPTION: Download input for year/day

# ==============================================================================
# ARGS
# ==============================================================================
year="$1"
day="$((10#$2))" # Day is base 10
session="$3"


# ==============================================================================
# SESSION
# ==============================================================================
if [[ -z "$session" ]]; then
	session_txt="$(git-top)/.session.txt"
	[[ -f "$session_txt" ]] && session="$(cat "$session_txt")"
fi


# ==============================================================================
# DOWNLOAD
# ==============================================================================
year="$((year % 100 + 2000))"
day="$(printf "%02d" "$day")"

url="https://adventofcode.com/${year}/day/$((10#${day}))/input"
printf "\e[34;1m%s\e[0m\n" "$url"
curl --cookie "session=$session" "$url"

