#!/usr/bin/env bash
# USAGE: bjobs [flags] | xbkill
# DESCRIPTION: bkill jobs

[[ -p /dev/stdin ]] && input="$(cat)" || input="$(bjobs "$@")"

while IFS= read -r line; do
	read -r jobid remain <<<"$line"
	[[ "$jobid" == "JOBID" ]] && continue
	print-info "$line"
	yesno "bkill?" && bkill "$jobid"
done <<< "$input"

