#!/usr/bin/env bash

# Create temp directory
tmpdir="$(mktemp -d)"
function finish() { rm -rf "$tmpdir"; }
trap finish EXIT

# Compile and run
in="$1" && shift
exe="$tmpdir/a.out"
gcc -o "$exe" -x c "$in" || exit $?
"$exe" "$@"

