#!/usr/bin/env bash
# USAGE: git-fix-first-merge-conflict <file>
# DESCRIPTION: Resolves the first merge conflict using AI
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

file="${1:?"Usage: $0 <file>"}"

start_line="$(awk '/^<<<<+ HEAD/ { print NR; exit }' "$file")"
end_line="$(awk '/^>>>>+/ { print NR; exit }' "$file")"
conflict="$(awk "NR >= $start_line && NR <= $end_line" "$file")"
print-info "Found conflict at lines $start_line-$end_line"

response="$(,ask merge "$conflict")"
print-header 'Full Response'; echo "$response"; echo

print-header 'Explanation'
explanation="$(awk '/Here is the merged code:/ {exit} 1;' <<<"$response")" || exit $?
echo "$explanation"
echo

print-header 'Merged Code'
code="$(awk '
	code && /^```/ {count++; next}
	(count==1)
	/Here is the merged code:/ {code=1}
' <<< "$response")" || exit $?
if [[ -z "$code" ]]; then
	print-error 'Code changes are empty.'
	exit 1
fi
echo "$code"
echo

print-header 'Summary'
summary="$(awk '
	(found && NF) {summary = summary $0 "\n"; next}
	/One-line summary:/ {found=1}
	END {print summary}
' <<< "$response")" || exit $?
echo "$summary"
echo

print-info 'Applying Merged Code'
awk-replace-chunk "$file" "$start_line" "$end_line" "$code"
retval=$?
print-retval "$retval"

git add "$file" || exit $?
read -r -d '' commit_message << EOF
[AI] $summary

$explanation
EOF
git commit -m  "$commit_message" "$file" || exit $?

