#!/usr/bin/env bash
# DESCRIPTION: Commit staged changes and edit commit message
git staged || exit $?

staged="$(git ls-staged)"
message="$staged"

ai_summary="$(NO_COLOR=1 git-ai-summary staged)"
if [[ -n "$ai_summary" ]]; then
	newline=$'\n'
	message+="${newline}${newline}AI Summary:"
	message+="${newline}$ai_summary"
fi

print-cmd git commit -m "$message"
git commit -m "$message" || exit $?

print-cmd git amend
git amend || exit $?

