#!/usr/bin/env bash
# DESCRIPTION: Commit staged changes and edit commit message
git staged || exit $?

staged="$(git ls-staged)"
summary="$(,commit)"

message="$(cat <<EOF
$staged

AI Summary:
$summary
EOF
)"

print-cmd git commit -m "$message"
git commit -m "$message" || exit $?

print-cmd git amend
git amend || exit $?

