#!/usr/bin/env bash
# USAGE: git ai-summarize <SHA>
# DESCRIPTION: Summarize a git commit using AI

commit="$1" || exit $?
[[ -n "$commit" ]] || { print-usage "$(basename "$0") <SHA>" >&2; exit 1; }

commit_info="$(git show "$commit")" || exit $?
top="$(git-top)" || exit $?

summary_txt="$top/.summary/${commit}.txt"
mkdir -p "$(dirname "$summary_txt")" || exit $?
if [[ -f "$summary_txt" ]]; then
	cat "$summary_txt"
	exit
fi

read -r -d '' system_prompt << EOF
<context>
You will be given the output of \`git show <sha>\`
</context>

<task>
Summarize the entire commit in a single sentence.
Use backticks for code and file names.
</task>

<format>
YYYY-MM-DD EMOJI One sentence summary.
</format>

<emojis>
🛠️ for fixes
🚨 for urgent fixes
✨ for new features
⚡ for performance optimizations
📝 for documentation
⚙️  for config changes
🚧  for WIP/experimental changes
⏪ for reverts
</emojis>
EOF

print-info "Summarizing ${commit}..."
summary="$(ai --system-prompt "$system_prompt" --prompt "$commit_info")" || exit $?
echo "$summary" > "$summary_txt"
cat "$summary_txt"

