#!/usr/bin/env bash
# USAGE: gitlab-rerun <pipeline_url>
# DESCRIPTION: Rerun failing pipelines from GitLab
url="$1"

# Get project ID from URL
url="${url#https://*/}"
read -r project pipeline_id <<<"$(sed -e 's:/-/pipelines/:\t:' <<<"$url")"
project_id="$(gitlab get-project-id "$project")"

data="per_page=100"

# Uncomment to debug:
data="include_retried=true&per_page=100"

all_jobs="$(gitlab curl "projects/$project_id/pipelines/$pipeline_id/jobs?$data")"
failed_jobs="$(jq -c '.[] | select(.status == "failed")' <<<"$all_jobs")"

# Uncomment to debug:
#echo "$all_jobs" | jq '.[] | {id,name,status}'
#echo "$failed_jobs" | jq '{id,name,status}'

while IFS= read -r job; do
	job_id="$(echo "$job" | jq -r .id)"
	name="$(echo "$job" | jq -r .name)"
	reason="$(echo "$job" | jq -r .failure_reason)"
	printf "\e[34;1m$name\e[0m - \e[31;1m%s\e[0m\n" "$reason"
	print-cmd gitlab curl "projects/$project_id/jobs/$job_id/trace"
	print-cmd gitlab curl "projects/$project_id/jobs/$job_id/retry" -X POST
	echo
done < <(jq -c <<<"$failed_jobs")

