#!/usr/bin/env bash
# USAGE: gitlab-users [search_string]
# DESCRIPTION: Find GitLab user(s)
(
	( gitlab-curl "users?username=$1" | jq -c '.[] | {id, username, name}' ) &
	( gitlab-curl "users?search=$1" | jq -c '.[] | {id, username, name}' ) &
) | sort | uniq | jq -c

