#!/usr/bin/env bash
# USAGE: gitlab-rerun <pipeline_url>
# DESCRIPTION: Rerun failing pipelines from GitLab
url="$1"

# Get project ID from URL
url="${url#https://*/}"
read -r project pipeline_id <<<"$(sed -e 's:/-/pipelines/:\t:' <<<"$url")"
project_id="$(gitlab get-project-id "$project")"

data="per_page=100"

# Uncomment to debug:
data="include_retried=true&per_page=100"

all_jobs="$(gitlab curl "projects/$project_id/pipelines/$pipeline_id/jobs?$data")"
failed_jobs="$(jq -c '.[] | select(.status != "success")' <<<"$all_jobs")"

# Uncomment to debug:
#echo "$all_jobs" | jq '.[] | {id,name,status}'
#echo "$failed_jobs" | jq '{id,name,status}'

tmpdir="$(mktemp -d)"
function cleanup { rm -rf "$tmpdir"; }
trap cleanup EXIT
cd "$tmpdir"

while IFS= read -r job; do
	job_id="$(echo "$job" | jq -r .id)"
	name="$(echo "$job" | jq -r .name)"
	reason="$(echo "$job" | jq -r .failure_reason)"
	#echo "$job"; exit

	if [[ "$reason" == 'null' ]]; then
		status="$(echo "$job" | jq -r .status)"
		printf "\e[34;1m$name\e[0m - \e[32;1m%s\e[0m\n" "$status"
		print-cmd gitlab curl "projects/$project_id/jobs/$job_id/trace"
		echo
		continue
	fi

	# Reasons:
	# - job_execution_timeout
	# - script_failure

	printf "\e[34;1m$name\e[0m - \e[31;1m%s\e[0m\n" "$reason"
	if [[ "$reason" == "script_failure" ]]; then
		print-cmd gitlab curl "projects/$project_id/jobs/$job_id/trace"
		gitlab curl "projects/$project_id/jobs/$job_id/trace" > "${project_id}_${job_id}.log"
	fi
	print-cmd gitlab curl "projects/$project_id/jobs/$job_id/retry" -X POST
	echo
done < <(jq -c <<<"$failed_jobs")

print-run pwd

