#!/usr/bin/env bash
# USAGE: gitlab-curl <endpoint>
# DESCRIPTION: curl GitLab API with authentication

API_KEY="$(cat "$HOME/.gitlab_key")" || exit $?
GITLAB_URL="$(cat "$HOME/.gitlab_url")" || exit $?

endpoint="${1:-user}"
shift

# Create a temporary file for the API token header
header_file="$(mktemp)"
function on_exit { rm -f "$header_file"; }
trap on_exit EXIT
printf "PRIVATE-TOKEN: $API_KEY" > "$header_file"
url="$GITLAB_URL/api/v4/$endpoint"

# gitlab-curl projects/<project>/jobs/<job_id>/trace -o job.log

curl -s --header @"$header_file" "$@" "$url"

