#!/usr/bin/env python3

import json
import os
import subprocess

MSG = 'swaymsg' if os.environ.get('WAYLAND_DISPLAY') else 'i3-msg'

output = subprocess.check_output([MSG, '-t', 'get_tree'])
tree = json.loads(output)

def print_container(tree, path = ''):
    for node in tree['nodes']:
        layout = node['layout']
        if node['name']:
            name = node['name'] + ' ' + f'<{layout}>'
        else:
            name = f'<{layout}>'
        #print(f'{path} {name}')
        print(f'{path}{name}')
        #print_container(node, f'{path}.{name}')
        print_container(node, f'  {path}')

print_container(tree)
