#!/usr/bin/env bash
msg=i3-msg; [[ -n "$WAYLAND_DISPLAY" ]] && msg=swaymsg
direction="$1"

tabbed=0

"$msg" fullscreen disable
i3-is-tabbed && tabbed=1
#notify-send "$(i3-is-tabbed)"
((tabbed)) && "$msg" focus parent
"$msg" focus "$direction"
((tabbed)) && "$msg" focus child
