#!/usr/bin/env bash
# TODO: Write awk script, show mode
config="$HOME/.config/i3/config"
[[ -n "$WAYLAND_DISPLAY" ]] && config="$HOME/.config/sway/config"
info="$(grep -E '^\s*bindsym|^\s*mode' "$config")"

tempfile="$(mktemp)"
function finish {
	rm -rf "$tempfile"
}
trap finish EXIT

echo "$info" > "$tempfile"
xless "$tempfile" & sleep 1
