#!/usr/bin/env bash
msg=i3-msg; [[ -n "$WAYLAND_DISPLAY" ]] && msg=swaymsg
workspace="$1"
print-run "$msg" "[workspace=$workspace]" move workspace to output current
#print-run "$msg" workspace --no-auto-back-and-forth "$workspace"
print-run "$msg" workspace "$workspace"
