#!/usr/bin/env bash
if [[ -n "$WAYLAND_DISPLAY" ]]; then
	print-cmd 'swaymsg -t get_outputs'
	swaymsg -t get_outputs | jq -r '.[] |
		"\(.name): \(if .active then "\(.current_mode.width)x\(.current_mode.height)@\((.current_mode.refresh / 1000) | round)Hz scale \(.scale) pos \(.rect.x),\(.rect.y)" else "off" end) — \(.make) \(.model)"'
	exit 0
fi

print-run xrandr --auto
print-run xrandr --listmonitors

print-cmd 'xrandr | grep connected'
xrandr | grep ' connected'
