#!/usr/bin/env bash
print-cmd date +'%Y%m%d-%H%M%S'
date +'%Y%m%d-%H%M%S'

echo
date +'%B %e, %Y'
printf '\e[33;1m%s\e[0m\n' "$(date '+%l:%M %p')"

echo
today="$(date +'%e')"
cal | grep --color=always -E "\b$today\b| "

