#!/usr/bin/env bash

exec 3>&1 1>&2

old_stty="$(stty -g)"
stty -icanon -echo
printf '\e[?25l'
trap 'stty "$old_stty"; printf "\e[?25h"' EXIT

dir="${1:-$PWD}"
dir="${dir%\/}"

left="$dir"
right=''

function redraw {
	local sep=''
	[[ -n "$right" ]] && sep='/'
	printf "\r\e[2K\e[34;1m%s\e[0m%s%s" "$left" "$sep" "$right"
}

redraw
while true; do
	key="$(getch.sh)"

	case "$key" in
		q)
			printf "\e[2K\r"
			exit 1
			;;
		h)
			# Shrink highlight: pop last segment of left into right
			[[ "$left" == */* ]] || continue
			segment="${left##*/}"
			left="${left%/*}"
			right="${right:+${segment}/${right}}"
			right="${right:-$segment}"
			redraw
			;;
		l)
			# Grow highlight: pop first segment of right into left
			[[ -n "$right" ]] || continue
			segment="${right%%/*}"
			if [[ "$right" == */* ]]; then
				right="${right#*/}"
			else
				right=''
			fi
			left="${left}/${segment}"
			redraw
			;;
		enter)
			printf "\e[2K\r"
			echo "$left" 1>&3
			exit 0
			;;
	esac

done
