#!/usr/bin/env bash
prompt='»'
#prompt='$'

exec 1>&2
printf "\e[34;1m%s\e[0m " "$prompt"

for arg in "$@"; do

	# Strip out API token
	arg="$(sed -E 's/(Authorization:.*sk-)\w+/\1REDACTED/' <<<"$arg")"

	clean_arg="$(printf '%q' "$arg")"

	if [[ "$arg" == "$clean_arg" ]]; then
		echo -n "$arg "
		continue
	fi

	if [[ $arg != *"'"* ]]; then
		clean_arg="'$arg'"
	elif [[ $arg != *'"'* ]]; then
		clean_arg="\"$arg\""
	fi
	echo -n "$clean_arg "
done
echo

