#!/usr/bin/env bash
for src in "$@"; do
	if ! [[ -e "$src" ]]; then
		echo "WARNING: '$src' not found."
		continue
	fi
	src="${src%/}"
	echo "rm -rf $src"
	(
		if [[ -d "$src" ]]; then
			empty="$(dirname "$src")/$(basename "$src").deleted.$$"
			mkdir "$empty"
			rsync -a --delete "$empty/" "$src/"
			rmdir "$empty" "$src"
		else
			rm -f "$src"
		fi
	) &>/dev/null &
done
