#!/usr/bin/env bash

PERCENTAGE="$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)"
CHARGING="$(pmset -g batt | grep 'AC Power')"

[[ "$PERCENTAGE" = "" ]] && exit 0

if ((PERCENTAGE>70)); then
	ICON=""
	ICON_COLOR='0xffff0000'
elif ((PERCENTAGE>50)); then
	ICON=""
	ICON_COLOR='0xffff0000'
elif ((PERCENTAGE>40)); then
	ICON=""
	ICON_COLOR='0xffff0000'
else
	ICON=""
	ICON_COLOR='0xffff0000'
fi

ICON_COLOR='0xffff0000'

if [[ "$CHARGING" != "" ]]; then
	ICON=""
	ICON_COLOR='0xffffff00'
fi

sketchybar --set "${NAME:-battery}" icon="$ICON" icon.color="$ICON_COLOR" label="${PERCENTAGE}%"

