#!/usr/bin/env python3
# USAGE: tmux-capture-pane
# DESCRIPTION: Capture and parse the current tmux pane contents,

import argparse
import json
import re
import subprocess

parser = argparse.ArgumentParser(description='Capture and parse the current tmux pane contents.')
parser.add_argument('--json', action='store_true', help='Output in JSON format')
args = parser.parse_args()

cmd = ['tmux', 'capture-pane', '-p', '-S', '-']
result = subprocess.run(cmd, capture_output=True)
pane_contents = result.stdout.decode('utf-8')

prompt_re = r'^todd.*»\s*(.*)$'
timestamp_re = '\[\d{2}:\d{2}:\d{2}\] (Started|Finished)'
exited_re = r'\(exited \d+\)'

in_command = False
output = ''
cmd_output = []

for line in pane_contents.splitlines():

    if re.search(exited_re, line): continue
    if re.search(timestamp_re, line): continue

    if match := re.match(prompt_re, line):
        if in_command:
            if command and output.strip():
                cmd_output.append((command, output.strip()))
            output = ''

        command = match.group(1).strip()
        in_command = True
        continue

    if in_command:
        output += f'{line}\n'

if args.json:
    cmd_output_json = [{'command': cmd, 'output': out} for cmd, out in cmd_output]
    print(json.dumps(cmd_output_json, indent=2))
    exit(0)

for command, output in cmd_output:
    print(f'$ {command}')
    if output.strip():
        print(output.strip())

