#!/usr/bin/env bash
# USAGE: youtube-song
# DESCRIPTION: Download song at highest quality

music_dir="$HOME/Music/Songs"
mkdir -p "$music_dir" || exit $?

args=()
args+=(--extractor-args "youtube:player_client=android")
args+=(--extract-audio)
args+=(--audio-format mp3)
args+=(-o "$music_dir/%(title)s.%(ext)s")
args+=("$@")
exec yt-dlp "${args[@]}"

